module.exports = {
	plugins: [
		require('autoprefixer'),
		require('postcss-filter-gradient')({
			skipWarnings: true,
		}),
		require('postcss-utilities'),
		require('postcss-pseudo-content-insert'),
		require('postcss-svg'),
		require('postcss-import'),
		require('postcss-nested'),
		require('postcss-sorting')({
			order: [
				{
					type: 'at-rule',
					name: '@import',
				},
				'custom-properties',
				'dollar-variables',
				{
					type: 'at-rule',
					name: '@util',
					parameter: 'position',
				},
				{
					type: 'at-rule',
					name: '@util',
					parameter: 'clearfix',
				},
				'declarations',
				{
					type: 'at-rule',
					name: '@media',
				},
				'rules',
				{
					type: 'rule',
					selector: '^&',
				},
			],
			'properties-order': [
				'composes',
				'position',
				'z-index',
				'top',
				'right',
				'bottom',
				'left',
				'transform',
				'float',
				'clear',
				'display',
				'flex-direction',
				'flex-wrap',
				'justify-content',
				'align-content',
				'align-item',
				'order',
				'flex-grow',
				'flex-shrink',
				'flex-basis',
				'align-self',
				'visibility',
				'overflow',
				'clip',
				'box-sizing',
				'width',
				'min-width',
				'max-width',
				'height',
				'min-height',
				'max-height',
				'margin',
				'padding',
				'color',
				'border',
				'border-top',
				'border-collapse',
				'border-spacing',
				'border-radius',
				'background',
				'box-shadow',
				'opacity',
				'font',
				'font-family',
				'font-size',
				'font-weight',
				'font-style',
				'font-variant',
				'font-size-adjust',
				'font-stretch',
				'font-effect',
				'font-emphasize',
				'font-emphasize-position',
				'font-emphasize-style',
				'font-smooth',
				'line-height',
				'letter-spacing',
				'white-space',
				'word-break',
				'text-overflow',
				'transition',
				'animation',
				'cursor',
				'outline',
				'outline-width',
				'outline-style',
				'outline-color',
				'outline-offset',
			],
			'unspecified-properties-position': 'bottom',
		}),
	],
};
